/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.parchmentmc.writtenbooks;

import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.parchmentmc.writtenbooks.versioning.VersioningManager;

public class WrittenBooksPlugin implements Plugin<Project> {

    public void apply(Project project) {
        project.getLogger().debug("Applying versioning manager.");
        VersioningManager.getInstance().apply(project);
    }
}
